dist: trusty
sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - DB=mysql
services:
  - mysql

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y cmake doxygen naturaldocs
  - gem install sass
  - sudo pip install mkdocs

before_script:
  - mkdir build
  - cd build
  - cmake .. -DWITH_EXPENSIVE_TESTS=YES
  - make && php www/db/configure_db_cli.php -p trustthetest -a install
  - make docs

script:
  - make lint
  - make check

matrix:
  include:
    - php: 5.5
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: nightly
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: hhvm
      env: DB=mariadb
      addons:
        mariadb: 10.1

  allow_failures:
    - php: nightly
    - php: hhvm
